### ISSUE TITLE
PyTorch 1.1 DLL load failed

### ISSUE THREAD

**Issue by Alexgolshtein** [hzli-ucas/warp-ctc_vs2015_pytorch1.0#1]
On torch 1.0.1 all woks OK, tests completed successfully,
 but using the following conf:

VS 2017, last update
python 3.6
torch            1.1.0
torchvision      0.3.0
DLL compiled successfully using VS 2017 and copied to "C:\********\virtualenv\pytorch\lib\site-packages\warpctc_pytorch-0.1-py3.6-win-amd64.egg\warpctc_pytorch\"

 I've got an error:

C:\******\warp-ctc\pytorch_binding> python .\tests\test_gpu.py
Traceback (most recent call last):
  File ".\tests\test_gpu.py", line 2, in <module>
    import warpctc_pytorch as warp_ctc
  File "C:\********\virtualenv\pytorch\lib\site-packages\warpctc_pytorch-0.1-py3.6-win-amd64.egg\warpctc_pytorch\__init__.py", line 6, in <module>
    from ._warp_ctc import *
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by hzli-ucas** [comment]
@Alexgolshtein Have you solved the problem? I try to follow your configuration using: `Win10 cuda10.1 anaconda3 python3.6 pytorch1.1 vs2017`. But everything works well, I cannot reproduce the error.
Are you sure the `warpctc.dll` is under the same path as your `__init__.py`?

**Comment by Alexgolshtein** [comment]
Step 1. Remove pytorch and warp-ctc 

`torch             1.0.1
torchvision       0.2.2.post3
warpctc-pytorch   0.1

Python 3.6.6
(pytorch) PS C:\> pip uninstall torch
Uninstalling torch-1.0.1:
  Would remove:
    c:\!work\virtualenv\pytorch\lib\site-packages\caffe2\*
    c:\!work\virtualenv\pytorch\lib\site-packages\torch-1.0.1.dist-info\*
    c:\!work\virtualenv\pytorch\lib\site-packages\torch\*
    c:\!work\virtualenv\pytorch\scripts\convert-caffe2-to-onnx.exe
    c:\!work\virtualenv\pytorch\scripts\convert-onnx-to-caffe2.exe
Proceed (y/n)? y
  Successfully uninstalled torch-1.0.1
(pytorch) PS C:\> pip uninstall torchvision
Uninstalling torchvision-0.2.2.post3:
  Would remove:
    c:\!work\virtualenv\pytorch\lib\site-packages\torchvision-0.2.2.post3.dist-info\*
    c:\!work\virtualenv\pytorch\lib\site-packages\torchvision\*
Proceed (y/n)? y
  Successfully uninstalled torchvision-0.2.2.post3
(pytorch) PS C:\> pip uninstall warpctc-pytorch
Uninstalling warpctc-pytorch-0.1:
  Would remove:
    c:\!work\virtualenv\pytorch\lib\site-packages\warpctc_pytorch-0.1-py3.6-win-amd64.egg
Proceed (y/n)? y
  Successfully uninstalled warpctc-pytorch-0.1
(pytorch) PS C:\> pip3 install torch===1.2.0 torchvision===0.4.0 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch===1.2.0
  Downloading https://download.pytorch.org/whl/cu100/torch-1.2.0-cp36-cp36m-win_amd64.whl (750.2MB)
     |████████████████████████████████| 750.2MB 22kB/s
Collecting torchvision===0.4.0
  Downloading https://download.pytorch.org/whl/cu100/torchvision-0.4.0-cp36-cp36m-win_amd64.whl (999kB)
     |████████████████████████████████| 1.0MB 6.4MB/s
Requirement already satisfied: numpy in c:\!work\virtualenv\pytorch\lib\site-packages (from torch===1.2.0) (1.16.2)
Requirement already satisfied: six in c:\!work\virtualenv\pytorch\lib\site-packages (from torchvision===0.4.0) (1.12.0)
Requirement already satisfied: pillow>=4.1.1 in c:\!work\virtualenv\pytorch\lib\site-packages (from torchvision===0.4.0) (6.0.0)
Installing collected packages: torch, torchvision
Successfully installed torch-1.2.0 torchvision-0.4.0`

Step 2: Get, Compile and Install warp-ctc: 
`torch             1.2.0
torchvision       0.4.0

Python 3.6.6

2.1 git pull
mkdir build
cd build
cmake -G "Visual Studio 15 2017 Win64" ..

2.2 Build solution using VS 2017 (project: ALL_BUILD; target: Release; platform x64)

2.3 Install egg to python (binding)

(pytorch) PS C:\> cd C:\!Work\NoRepos\warp-ctc\pytorch_binding
(pytorch) PS C:\!Work\NoRepos\warp-ctc\pytorch_binding> python .\setup.py install
Could not find warpctc.dll in ../build/Release.
Build warp-ctc and set WARP_CTC_PATH to the location of warpctc.dll (default is '%s')
(pytorch) PS C:\!Work\NoRepos\warp-ctc\pytorch_binding> python .\setup.py install
running install
running bdist_egg
running egg_info
writing warpctc_pytorch.egg-info\PKG-INFO
writing dependency_links to warpctc_pytorch.egg-info\dependency_links.txt
writing top-level names to warpctc_pytorch.egg-info\top_level.txt
reading manifest file 'warpctc_pytorch.egg-info\SOURCES.txt'
writing manifest file 'warpctc_pytorch.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
C:\!Work\virtualenv\pytorch\lib\site-packages\torch\utils\cpp_extension.py:189: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\warpctc_pytorch
copying build\lib.win-amd64-3.6\warpctc_pytorch\_warp_ctc.cp36-win_amd64.pyd -> build\bdist.win-amd64\egg\warpctc_pytorch
copying build\lib.win-amd64-3.6\warpctc_pytorch\__init__.py -> build\bdist.win-amd64\egg\warpctc_pytorch
byte-compiling build\bdist.win-amd64\egg\warpctc_pytorch\__init__.py to __init__.cpython-36.pyc
creating stub loader for warpctc_pytorch\_warp_ctc.cp36-win_amd64.pyd
byte-compiling build\bdist.win-amd64\egg\warpctc_pytorch\_warp_ctc.py to _warp_ctc.cpython-36.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying warpctc_pytorch.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying warpctc_pytorch.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying warpctc_pytorch.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying warpctc_pytorch.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
writing build\bdist.win-amd64\egg\EGG-INFO\native_libs.txt
zip_safe flag not set; analyzing archive contents...
warpctc_pytorch.__pycache__._warp_ctc.cpython-36: module references __file__
creating 'dist\warpctc_pytorch-0.1-py3.6-win-amd64.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing warpctc_pytorch-0.1-py3.6-win-amd64.egg
creating c:\!work\virtualenv\pytorch\lib\site-packages\warpctc_pytorch-0.1-py3.6-win-amd64.egg
Extracting warpctc_pytorch-0.1-py3.6-win-amd64.egg to c:\!work\virtualenv\pytorch\lib\site-packages
Adding warpctc-pytorch 0.1 to easy-install.pth file

Installed c:\!work\virtualenv\pytorch\lib\site-packages\warpctc_pytorch-0.1-py3.6-win-amd64.egg
Processing dependencies for warpctc-pytorch==0.1
Finished processing dependencies for warpctc-pytorch==0.1

2.4 Check:
(pytorch) PS C:\!Work\NoRepos\warp-ctc\pytorch_binding> pip list | grep torch
torch             1.2.0
torchvision       0.4.0
warpctc-pytorch   0.1

2.5 Copy warpctc.dll 
from  
C:\!Work\NoRepos\warp-ctc\build\Release
to
C:\!Work\virtualenv\pytorch\Lib\site-packages\warpctc_pytorch-0.1-py3.6-win-amd64.egg\warpctc_pytorch

2.6 Run tests

(pytorch) PS C:\!Work\NoRepos\warp-ctc\pytorch_binding> python tests/test_cpu.py
Traceback (most recent call last):
  File "tests/test_cpu.py", line 2, in <module>
    import warpctc_pytorch as warp_ctc
  File "C:\!Work\virtualenv\pytorch\lib\site-packages\warpctc_pytorch-0.1-py3.6-win-amd64.egg\warpctc_pytorch\__init__.py", line 6, in <module>
    from ._warp_ctc import *
ImportError: DLL load failed: The specified module could not be found.
(pytorch) PS C:\!Work\NoRepos\warp-ctc\pytorch_binding> python tests/test_gpu.py
Traceback (most recent call last):
  File "tests/test_gpu.py", line 2, in <module>
    import warpctc_pytorch as warp_ctc
  File "C:\!Work\virtualenv\pytorch\lib\site-packages\warpctc_pytorch-0.1-py3.6-win-amd64.egg\warpctc_pytorch\__init__.py", line 6, in <module>
    from ._warp_ctc import *
ImportError: DLL load failed: The specified module could not be found.                                                                                                                                                  
`

**Comment by hzli-ucas** [comment]
@Alexgolshtein
Just install warp-ctc with torch 1.2.0 and torchvision 0.4.0, and everything works well for me. Don't know what's the problem. Try the following to see if you can bypass it:

Copy the whole folder `warpctc_pytorch` from where it's been installed, i.e.
`C:!Work\virtualenv\pytorch\lib\site-packages\warpctc_pytorch-0.1-py3.6-win-amd64.egg\`
to the same direction of the test files, i.e.
`C:!Work\NoRepos\warp-ctc\pytorch_binding\tests\`.
And be sure the folder containing the following files:
`__init__.py`, `_warp_ctc.py`, `warpctc.dll`, `_warp_ctc.cp36-win_amd64.pyd`

**Comment by Alexgolshtein** [comment]
Sure. I copied dll to *egg. 
Currently I can't try to copy the content of egg to test directory - I've reinstalled pytorch (1.2), cloned repo again and then can't build at all.  ATen and c10 necessary files missing.

C:\!Work\virtualenv\pytorch\lib\site-packages\torch\include\c10/cuda/CUDAStream.h(171): warning C4251: 'c10::cuda::CUDAStream::stream_': class 'c10::Stream' needs to have dll-interface to be used by clients of class 'c10::cuda::CUDAStream' C:\!Work\virtualenv\pytorch\lib\site-packages\torch\include\c10/core/Stream.h(57): note: see declaration of 'c10::Stream'
src/binding.cpp(10): fatal error C1083: Cannot open include file: 'ATen/cuda/CUDAGuard.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

If I replace ATen directory with another one from torch repo:

binding.cpp
C:\!Work\virtualenv\pytorch\lib\site-packages\torch\include\ATen/core/Allocator.h(6): fatal error C1083: Cannot open include file: 'c10/Device.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by hzli-ucas** [comment]
@Alexgolshtein
Don't worry, this is a small problem. Comment out or just delete `ATen/cuda/CUDAGuard.h` at line 10 of the `binding.cpp` file. And build again.

**Comment by Alexgolshtein** [comment]
Success! Big thanks!
What I've done:
1. Cloned again the repo.
2. Recreated virtual env (Python 3.6.6). Installed pytorch 1.2.0 & torchvision 0.4.0, numpy & pytest
3. Build all by manual
4. Commented "ATen/cuda/CUDAGuard.h in the｀binding.cpp` file. " according to your instructions.
5. Installed "binding"
6. Copied dll to egg folder
7. Created Set system and user variables named "WARP_CTC_PATH" to folder with dll (egg folder)
8. Tests succeed!

Additionally I've tested with Python 3.7 - Everything OK.
Thank You!
