### ISSUE TITLE
occur an error when running python setup.py install

### ISSUE THREAD

**Issue by Leedorado** [hzli-ucas/warp-ctc_vs2015_pytorch1.0#2]
my enviroment: win10+cuda10+python3.6+pytorch1.2.0+vs2015
the error is as below:
 fatal error C1083: 无法打开包括文件: “ATen/cuda/CUDAGuard.h”: No such file or directory
could you please help me out,thx~~

**Comment by tadas-subonis** [comment]
I've ran into the same issue

**Comment by tadas-subonis** [comment]
Apparently, ```src\binding.cpp``` is out-of-date, and the file
```
#include "ATen/cuda/CUDAGuard.h"
```
no longer exists.

It should be:
```
#include "c10/cuda/CUDAGuard.h"
```
