### ISSUE TITLE
failed install in Windows 

### ISSUE THREAD

**Issue by lmw0320** [hzli-ucas/warp-ctc_vs2015_pytorch1.0#3]
I have downloaded the zip file and installed it by " pip install ***",  Unfortunately, I get the error as below, could you help to solve it, thanks in advance.
![1](https://user-images.githubusercontent.com/37755235/90370934-c99b2a80-e0a0-11ea-9f24-e73f9fb6378f.png)

**Comment by hzli-ucas** [comment]
Did you try to follow the instructions in README? You will have to manually compile the cpp files, then install the bindings step by step. We didn't offer any way, like a single "pip install" command, to build the project in one step.

**Comment by lmw0320** [comment]
thanks for reply. It seems the bindings are under Linux system, not suit for Windows?
By the way, I have install pytorch with version=1.2.0, Is the CTCloss under pytorch same as this CTCLoss?

**Comment by hzli-ucas** [comment]
@lmw0320 
All the instructions in [README](https://github.com/hzli-ucas/warp-ctc/blob/vs2017/README.md) are for Windows system.  Don't worry, just follow the steps.
We didn't test with pytorch 1.2, but we think this won't be a problem so long as the installation works well with v1.0 and v1.1.
If there is any other problems, please feel free to contact us.
